name: model_06
entity: evhenia-k-you
program: main_wandb.py
method: grid
metric:
  goal: maximize
  name: test/accuracy
parameters:
  model:
    value: model06
  opt:
    value: NAdam
  epochs:
    values: [25, 38, 50]
  batch_size:
    values: [32, 45, 64]